### ISSUE TITLE
Regarding minSDKVersion

### ISSUE THREAD

**Issue by Dvik** [BenGoBlue05/UdacityAlumni#16]
Should be minSDKVersion be as high as 21? I believe it should be 16 or 17 so that the app runs on more than 95% of the devices. @BenGoBlue05

**Comment by BenGoBlue05** [comment]
you're absolutely right. the app should be compat with lower version devices. However, for the beginning stages for this project I wanted to simplify things as much as possible so developers of all skill levels can get involved - in this case worrying about backwards compat - So this and some other issues might not be 'best practice'

**Comment by Dvik** [comment]
Cool. Closing this out for now.
